version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python -m pytest

workflows:
  build-and-test-workflow:
    jobs:
      - test
